log:
  level:                   error
  file:                    ''

plugin:
  - tag:                   main_server
    type:                  server
    args:
      entry:
        - _no_ecs
        - lazy_cache
        - _prefer_ipv4
        - main_sequence
      server:
        - protocol:        udp
          addr:            ':5335'
        - protocol:        tcp
          addr:            ':5335'
          
  - tag:                   main_sequence
    type:                  sequence
    args:
      exec:
        - if:
            - query_is_local_domain
            - '!_query_is_common'
          exec:
            - forward_local
            - _return
        - if:
            - query_is_non_local_domain
          exec:
            - forward_remote
            - _return
        - forward_local
        - if:
            - response_has_local_ip
          exec:
            - _return 
        - forward_remote

  - tag:                   forward_local
    type:                  fast_forward
    args:
      upstream:
        - addr:            'https://223.5.5.5/dns-query'
  - tag:                   forward_remote
    type:                  fast_forward
    args:
      upstream:
        - addr:            'tls://8.8.4.4'
          idle_timeout:    5
        - addr:            'tls://1.0.0.1'
          idle_timeout:    5
        - addr:            'tls://9.9.9.9'
          idle_timeout:    5

  - tag:                   lazy_cache
    type:                  cache
    args:
      size:                512000
      lazy_cache_ttl:      259200

  - tag:                   query_is_local_domain
    type:                  query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:cn'

  - tag:                   query_is_non_local_domain
    type:                  query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:geolocation-!cn'

  - tag:                   response_has_local_ip
    type:                  response_matcher
    args:
      ip:
        - 'ext:./all_cn.txt'
        - 'ext:./all_cn_ipv6.txt'
