log:
  level:                   error
  file:                    ''

plugin:
  - tag:                   main_server
    type:                  server
    args:
      entry:
        - _no_ecs
        - lazy_cache
        - _prefer_ipv4
        - main_sequence
      server:
        - protocol:        udp
          addr:            '[::]:5335'
        - protocol:        tcp
          addr:            '[::]:5335'

  - tag:                   main_sequence
    type:                  sequence
    args:
      exec:
        - if:
            - qtype65
          exec:
            - block
            - _return
        - if:
            - query_is_local_domain
            - '!_query_is_common'
          exec:
            - forward_local
            - _return
        - if:
            - query_is_non_local_domain
          exec:
            - forward_remote
            - _return
        - forward_local
        - if:
            - response_has_local_ip
          exec:
            - _return 
        - forward_remote

  - tag:                   forward_local
    type:                  forward
    args:
      upstream:
        - addr:            'https://dns.alidns.com/dns-query'
        - addr:            'https://doh.pub/dns-query'
      bootstrap:
        -                  'https://223.5.5.5/dns-query'
  - tag:                   forward_remote
    type:                  forward
    args:
      upstream:
        - addr:            'https://doh.opendns.com/dns-query'
        - addr:            'https://dns10.quad9.net/dns-query'
        - addr:            'https://dns.cloudflare.com/dns-query'
      bootstrap:
        -                  'https://223.6.6.6/dns-query'

  - tag:                   lazy_cache
    type:                  cache
    args:
      size:                512000
      lazy_cache_ttl:      259200

  - tag:                   qtype65
    type:                  query_matcher
    args:
      qtype:               [65]

  - tag:                   block
    type:                  blackhole
    args:
      rcode:               0
      ipv4:                '127.0.0.1'
      ipv6:                '::1'

  - tag:                   query_is_local_domain
    type:                  query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:cn'

  - tag:                   query_is_non_local_domain
    type:                  query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:geolocation-!cn'

  - tag:                   response_has_local_ip
    type:                  response_matcher
    args:
      ip:
        - 'ext:./cn.dat:cn'
