log:
  level:                   error
  file:                    ''

plugin:
  - tag:                   main_server
    type:                  server
    args:
      entry:
        - _no_ecs
        - lazy_cache
        - _prefer_ipv4
        - main_sequence
      server:

        - protocol:        udp
          addr:            127.0.0.1:5335
        - protocol:        tcp
          addr:            127.0.0.1:5335
        - protocol:        udp
          addr:            '[::1]:5335'
        - protocol:        tcp
          addr:            '[::1]:5335'

  - tag:                   main_sequence
    type:                  sequence
    args:
      exec:
        - if:
            - query_is_qtype65
          exec:
            - _block_with_nxdomain
            - _return
        - if:
            - query_is_local_domain
            - "!_query_is_common"
          exec:
            - forward_local
            - _return
        - if:
            - query_is_non_local_domain
          exec:
            - forward_remote
            - _return
        - primary:
            - forward_local
            - if:
                - "!response_has_local_ip"
              exec:
                - _drop_response
          secondary:
            - forward_remote
          fast_fallback: 150
          always_standby: true

  - tag:                   forward_local
    type:                  fast_forward
    args:
      upstream:
        - addr:            'https://223.5.5.5/dns-query'
        - addr:            'https://1.12.12.12/dns-query'
  - tag:                   forward_remote
    type:                  fast_forward
    args:
      upstream:
        - addr:            'https://208.67.222.222/dns-query'
        - addr:            'https://9.9.9.9/dns-query'
        - addr:            'tls://8.8.4.4'

  - tag:                   lazy_cache
    type:                  cache
    args:
      size:                512000
      lazy_cache_ttl:      259200

  - tag:                   query_is_qtype65
    type:                  query_matcher
    args:
      qtype:               [65]

  - tag:                   query_is_local_domain
    type:                  query_matcher
    args:
      domain:
        - 'ext:./chinalist.txt'

  - tag:                   query_is_non_local_domain
    type:                  query_matcher
    args:
      domain:
        - 'ext:./gfwlist.txt'

  - tag:                   response_has_local_ip
    type:                  response_matcher
    args:
      ip:
        - 'ext:./geoip.dat:cn'

