name: Update-CI

on:
  schedule:
    - cron: 0 16 * * *
  watch:
    types: [started]
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - uses: actions/checkout@master

      - name: Run generate script
        run: |
          wget https://raw.githubusercontent.com/Loyalsoldier/geoip/release/cn.dat -nv -O ./luci-app-mosdns/root/etc/mosdns/geoip.dat
          wget https://raw.githubusercontent.com/Loyalsoldier/domain-list-custom/release/geosite.dat -nv -O ./luci-app-mosdns/root/etc/mosdns/geosite.dat
          latest_commit="$(curl -s https://github.com/IrineSistiana/mosdns/commits/main | grep -E '"Copy the full SHA"' | awk -F 'value="' '{print $2}' | cut -b 1-7 | sed -n 1p)"
          sed -i '/PKG_VERSION:/d' ./mosdns/Makefile
          sed -i "7 a PKG_VERSION:=$latest_commit" ./mosdns/Makefile
          chmod -R 755 ./luci-app-mosdns/root/etc/mosdns/*.sh
      - name: Commit file
        run: |
          git config --global user.email admin@outlook.com
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Update `date +%Y/%m/%d\ %H:%M:%S\ %Z`" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}

      - name: Cleanup Workflow Logs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
