name: Update-CI
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      
      - name: Run generate script
        run: |
          wget https://raw.githubusercontent.com/Loyalsoldier/geoip/release/cn.dat -nv -O ./luci-app-mosdns/root/etc/mosdns/geoip.dat
          wget https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf -nv -O ./luci-app-mosdns/root/etc/mosdns/accelerated-domains.china.txt
          wget https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/apple.china.conf -nv -O ./luci-app-mosdns/root/etc/mosdns/apple.china.txt
          wget https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/google.china.conf -nv -O ./luci-app-mosdns/root/etc/mosdns/google.china.txt
          cat ./luci-app-mosdns/root/etc/mosdns/accelerated-domains.china.txt ./luci-app-mosdns/root/etc/mosdns/apple.china.txt ./luci-app-mosdns/root/etc/mosdns/google.china.txt | sort | uniq > ./luci-app-mosdns/root/etc/mosdns/chinalist.txt
          sed -i 's/server=\///g;s/\/114.114.114.114//g' ./luci-app-mosdns/root/etc/mosdns/chinalist.txt
          wget https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt -nv -O ./luci-app-mosdns/root/etc/mosdns/gfw.txt
          wget https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/greatfire.txt -nv -O ./luci-app-mosdns/root/etc/mosdns/greatfire.txt
          cat ./luci-app-mosdns/root/etc/mosdns/gfw.txt ./luci-app-mosdns/root/etc/mosdns/greatfire.txt | sort | uniq > ./luci-app-mosdns/root/etc/mosdns/gfwlist.txt
          rm ./luci-app-mosdns/root/etc/mosdns/accelerated-domains.china.txt ./luci-app-mosdns/root/etc/mosdns/apple.china.txt ./luci-app-mosdns/root/etc/mosdns/google.china.txt ./luci-app-mosdns/root/etc/mosdns/gfw.txt ./luci-app-mosdns/root/etc/mosdns/greatfire.txt
          #latest_commit="$(curl -s https://github.com/IrineSistiana/mosdns/commits/main | grep -E '"Copy the full SHA"' | awk -F 'value="' '{print $2}' | cut -b 1-7 | sed -n 1p)"
          #sed -i '/PKG_VERSION:/d' ./mosdns/Makefile
          #sed -i "7 a PKG_VERSION:=$latest_commit" ./mosdns/Makefile
          chmod -R 755 ./luci-app-mosdns/root/etc/mosdns/*.sh
      - name: Commit file
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Update `date +%Y/%m/%d\ %H:%M:%S\ %Z`" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
      - name: Cleanup Workflow Logs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
